# Generated by Django 2.2.6 on 2019-12-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environments',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=255)),
                ('grid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('image_path', models.TextField()),
                ('texture_path', models.TextField()),
                ('in_category', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('num_of_photos', models.IntegerField()),
            ],
        ),
    ]
