# Generated by Django 2.2.6 on 2019-12-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('trial_id', models.IntegerField()),
                ('correct', models.BooleanField()),
                ('input_start', models.DateTimeField()),
                ('input_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TrialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('env_id', models.IntegerField()),
                ('trial_start', models.DateTimeField()),
                ('trial_end', models.DateTimeField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
