# Generated by Django 2.2.6 on 2020-01-21 19:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialdata',
            name='id',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='undo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='user_decision_points',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='trialdata',
            name='trial_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
