# Generated by Django 2.2.6 on 2020-01-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_auto_20200121_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialdata',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trialdata',
            name='trial_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trialdata',
            name='trial_start',
            field=models.DateTimeField(null=True),
        ),
    ]
